# Generated by Django 5.2 on 2025-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear_value',
            name='topic',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
