# Generated by Django 5.2 on 2025-05-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gearapp', '0002_gear_value_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear_value',
            name='topic',
        ),
    ]
